### ISSUE TITLE
Develop first iteration of ESI Cluster Orchestrator

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/python-esiclient#59]
One use case of ESI is creating a small bare metal cluster. Doing so using OpenStack commands is painstaking, time consuming, and a little intimidating. An orchestration commands that takes in a single configuration may help here, especially since that configuration can be shared from user to user making initial orchestration a breeze.

**Comment by tzumainn** [comment]
@joachimweyl I don't see this on the zenhub board anymore - did it disappear somehow?

**Comment by joachimweyl** [comment]
I migrated it from esi repo to this repo and this repo needed to be added to ZenHub to show up on the workspace. I have added this repo to our ZenHub Workspace.
